version: '3.4'

services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - "5432:5432" #default port of postgres:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data #store the data from this add to volume postgres data such that upon shutting off, the data is still stored in our local machine
    environment:
       POSTGRES_USER: postgres #Use this in DATABASE_URL-user in .env
       POSTGRES_DB: threads #db name
       POSTGRES_PASSWORD: 1234 #do not use @ -password

volumes:
  postgres_data:
